[package]
name = "spider"
version = "0.1.0"
edition = "2018"

[dependencies]
crossterm = "0.20"
rand = { version = "0.8", features = ["serde1"] }
rand_xoshiro = { version = "0.6", features = ["serde1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3"
